FROM node:18.2

WORKDIR /app

COPY package*.json ./

RUN npm update && \ 
    npm install

COPY . .

WORKDIR /app/server

RUN npm init -y && \
    npm update && \
    npm install && \
    npm install express mongodb@3.5.7

EXPOSE 9000

CMD ["npm", "run", "server:dev"]
